"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var inversify_1 = require("inversify");
require("reflect-metadata");
var jsonService_1 = require("./jsonService");
var dbService_1 = require("./dbService");
var envService_1 = require("./envService");
var boardService_1 = require("./boardService");
var types_1 = require("../models/types");
var container = new inversify_1.Container();
exports.container = container;
container.bind(types_1.TYPES.JsonInterface).to(jsonService_1.JsonService);
container.bind(types_1.TYPES.DbInterface).to(dbService_1.DbService);
container.bind(types_1.TYPES.EnvInterface).to(envService_1.EnvService);
container.bind(types_1.TYPES.BoardInterface).to(boardService_1.BoardService);
