sudo: false
language: node_js
node_js:
- '8'
cache:
  directories:
  - node_modules
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH="$HOME/.yarn/bin:$PATH"
- yarn upgrade
install:
- yarn
jobs:
  include:
  - stage: test
    script:
    - yarn coveralls
